# Services: MongoDB, backend API, and frontend
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env        
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskdb
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongodb_data: